<a href="https://colab.research.google.com/github/AleR26/ColabFiles/blob/main/Tarea%20factorizacion%20de%20matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Taller: Factorización de Matrices en Ciencia de Datos

In [7]:
import numpy as np
from scipy.linalg import lu, cholesky, qr, svd

# Matriz B diagonalmente predominante
A = np.array([[57/4, 15/2, -2],
              [-2, 15/2, -3],
              [-3, -2, 15/2]], dtype=float)

## Descomponer A=LU y verificar la reconstrucción.

In [8]:
P, L, U = lu(A)
print("Matriz L:\n", L)
print("Matriz U:\n", U)

# Verificación
print("Reconstrucción:\n", P @ L @ U)

print("Multiplicacion:\n",P@A)

Matriz L:
 [[ 1.          0.          0.        ]
 [-0.14035088  1.          0.        ]
 [-0.21052632 -0.04923077  1.        ]]
Matriz U:
 [[14.25        7.5        -2.        ]
 [ 0.          8.55263158 -3.28070175]
 [ 0.          0.          6.9174359 ]]
Reconstrucción:
 [[14.25  7.5  -2.  ]
 [-2.    7.5  -3.  ]
 [-3.   -2.    7.5 ]]
Multiplicacion:
 [[14.25  7.5  -2.  ]
 [-2.    7.5  -3.  ]
 [-3.   -2.    7.5 ]]


## Descomponer A = QR

In [9]:
Q, R = qr(A)
print("Matriz Q:\n", Q)
print("Matriz R:\n", R)
print("Reconstrucción:\n", Q @ R)

Matriz Q:
 [[-0.96944944 -0.12299584  0.21222582]
 [ 0.13606308 -0.9895342   0.04805113]
 [ 0.20409462  0.07545924  0.97603857]]
Matriz R:
 [[-14.6990646   -6.65858697   3.0614193 ]
 [  0.          -8.49489373   3.78053856]
 [  0.           0.           6.75168424]]
Reconstrucción:
 [[14.25  7.5  -2.  ]
 [-2.    7.5  -3.  ]
 [-3.   -2.    7.5 ]]


## Descomponer y Analizar valores singulares

In [10]:
U, s, Vt = svd(A)
print("Valores singulares:", s)
print("Reconstrucción:\n", U @ np.diag(s) @ Vt)

Valores singulares: [17.18718361  8.59178773  5.70915083]
Reconstrucción:
 [[14.25  7.5  -2.  ]
 [-2.    7.5  -3.  ]
 [-3.   -2.    7.5 ]]
