<a href="https://colab.research.google.com/github/AleR26/ColabFiles/blob/main/Practica%203/CrearMatriz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Manipulación de matrices

---



Manipilacion de matrices

In [ ]:
arrA = np.random.randint(1, 10, (3, 3))
arrB = np.random.randint(1, 10, (3, 3))

print("Matriz A:")
print(arrA)
print("Matriz B:")
print(arrB)
print("Suma de matrices:", arrA + arrB)
print("Resta de matrices:", arrA - arrB)
print("Multiplicar la primer matriz por 2", arrA*2)
print("Multiplicación matricial:", np.dot(arrA, arrB))

Matriz A:
[[9 4 9]
 [5 2 6]
 [4 7 3]]
Matriz B:
[[5 3 4]
 [2 6 1]
 [8 8 3]]
Suma de matrices: [[14  7 13]
 [ 7  8  7]
 [12 15  6]]
Resta de matrices: [[ 4  1  5]
 [ 3 -4  5]
 [-4 -1  0]]
Multiplicar la primer matriz por 2 [[18  8 18]
 [10  4 12]
 [ 8 14  6]]
Multiplicación matricial: [[125 123  67]
 [ 77  75  40]
 [ 58  78  32]]
