<a href="https://colab.research.google.com/github/AleR26/ColabFiles/blob/main/Practica4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Manipulación de matrices

---



In [2]:
import numpy as np

In [3]:
arrA = np.random.randint(1, 10, (3, 3))
arrB = np.random.randint(1, 10, (3, 3))

print("Matriz A:")
print(arrA)
print("Matriz B:")
print(arrB)
print("Suma de matrices:", arrA + arrB)
print("Resta de matrices:", arrA - arrB)
print("Multiplicar la primer matriz por 2", arrA*2)
print("Multiplicación matricial:", np.dot(arrA, arrB))

Matriz A:
[[8 7 2]
 [1 4 8]
 [6 7 9]]
Matriz B:
[[4 9 9]
 [4 4 5]
 [1 7 2]]
Suma de matrices: [[12 16 11]
 [ 5  8 13]
 [ 7 14 11]]
Resta de matrices: [[ 4 -2 -7]
 [-3  0  3]
 [ 5  0  7]]
Multiplicar la primer matriz por 2 [[16 14  4]
 [ 2  8 16]
 [12 14 18]]
Multiplicación matricial: [[ 62 114 111]
 [ 28  81  45]
 [ 61 145 107]]
