<a href="https://colab.research.google.com/github/AleR26/ColabFiles/blob/main/Practica%203/CrearMatriz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Creación de un arreglo y operaciones básicas

In [2]:
import numpy as np

arr = np.random.randint(1,101,20) #inicio,fin,cantidad de datos [1,101)
print("Array: " + str(arr))
print("Valor máximo: " + str(np.max(arr)))
print("Valor minimo: " + str(np.min(arr)))
print("Promedio: " + str(np.mean(arr)))
print("Sumar 10 a cada elemento: " + str(arr+10))

Array: [  5  79  65  45 100  54  10  55  71  80  70  70  46  83  85  43  13  14
  36  39]
Valor máximo: 100
Valor minimo: 5
Promedio: 53.15
Sumar 10 a cada elemento: [ 15  89  75  55 110  64  20  65  81  90  80  80  56  93  95  53  23  24
  46  49]


Manipilacion de matrices

In [6]:
arrA = np.random.randint(1, 10, (3, 3))
arrB = np.random.randint(1, 10, (3, 3))

print("Matriz A:")
print(arrA)
print("Matriz B:")
print(arrB)
print("Suma de matrices:", arrA + arrB)
print("Resta de matrices:", arrA - arrB)
print("Multiplicar la primer matriz por 2", arrA*2)
print("Multiplicación matricial:", np.dot(arrA, arrB))

Matriz A:
[[9 4 9]
 [5 2 6]
 [4 7 3]]
Matriz B:
[[5 3 4]
 [2 6 1]
 [8 8 3]]
Suma de matrices: [[14  7 13]
 [ 7  8  7]
 [12 15  6]]
Resta de matrices: [[ 4  1  5]
 [ 3 -4  5]
 [-4 -1  0]]
Multiplicar la primer matriz por 2 [[18  8 18]
 [10  4 12]
 [ 8 14  6]]
Multiplicación matricial: [[125 123  67]
 [ 77  75  40]
 [ 58  78  32]]
